/*

This is a JavaScript file you can edit to add custom markers to the map.
uNmINeD does not overwrite this file during map generation.

Steps:

    1. Edit this file using Notepad or a code editor (do not use document editors like Microsoft Word)
    2. Change the line "isEnabled: false," to "isEnabled: true," to display the markers
    3. Change or remove the example markers
    4. Add your own markers

Marker format:

    {
        x: X coordinate of the marker (in Minecraft block units),
        z: Z coordinate of the marker (in Minecraft block units),
        image: marker image URL to display (in quotes),
        imageScale: scale of the image (e.g. 1 = display full size, 0.5 = display half size),
        imageAnchor: [0.5, 1] means the tip of the pin is at the center-bottom of the image (see OpenLayers documentation for more info),
        text: marker text do display (in quotes),
        textColor: text color in HTML/CSS format (in quotes),
        offsetX: horizontal pixel offset of the text,
        offsetY: vertical pixel offset of the text,
        font: text font in HTML/CSS format (in quotes),
    },

Things to keep in mind:

* There are opening and closing brackets for each marker "{" and "}"
* Property names are case sensitive (i.e. "textColor" is okay, "TextColor" is not)
* There is a comma (",") at the end of each line except the opening brackets ("{")

You can use https://mapmarker.io/editor to generate custom pin images.
Use the imageScale property if the pin image is too large.

*/

UnminedCustomMarkers = {

    isEnabled: true,

    markers: [

        // Example 1: Simple marker
/*        {
            x: -200,
            z: -200,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
        },*/

        // Example 2: Marker with text
        {
            x: 0,
            z: 0,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "World Center 0/0",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        // Example 3: Text only
/*        {
            x: 200,
            z: 200,
            text: "Text only", 
            textColor: "yellow", 
            offsetX: 0,
            offsetY: 0, 
            font: "bold 50px Calibri,sans serif",
        },
*/
        // add your markers here
        {
            x: 3064,
            z: 4,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Spawn",
            textColor: "black",
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1513,
            z: -384,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Sam's Town",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1817,
            z: -650,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Raid | Iron Farm",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 2282,
            z: -557,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Clament Siren's Base",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1750,
            z: -777,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Slime Farm",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 2296,
            z: 136,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "HipHopScotch's Base",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1847,
            z: -947,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Gavin's Base",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1824,
            z: -925,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Gabi's House",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1697,
            z: -991,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Frog Light Farm",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1354,
            z: -1960,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Guardian/Fish/Squid Farm",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 1400,
            z: -1933,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Fisherman Trading Hall",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 3227,
            z: -307,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Spawn Village Trading Hall & Farms",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 3300,
            z: -107,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Powdered Snow Farm",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 3237,
            z: -125,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Skeleton / Stray Farm",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                {
            x: 3591,
            z: 1400,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Underwater Trading Hall",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                        {
            x: 3460,
            z: 1420,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Schwvevils Base",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                        {
            x: 2900,
            z: -6300,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Large Mangrove Swamp",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 7650,
            z: 709,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Mushroom Island",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 3820,
            z: 4670,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Mushroom Island",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 1077,
            z: -585,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Clament Siren's Creeper Farm",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: -3720,
            z: -250,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "QuarryMan's Base",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                {
            x: 2183,
            z: 110,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "HipHopScotch's Trading Hall",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                        {
            x: 1912,
            z: 648,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "No Idea? What is this?",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                        {
            x: 3525,
            z: -5658,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Wither Battle Base",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                {
            x: -144,
            z: -1312,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Small Cherry Blossom Biome",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                {
            x: 3609,
            z: -495,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Unknown Player Base - Possibly ArcusCrow",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                {
            x: 1969,
            z: -792,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Mr Wink's Gold Farm",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                        {
            x: -1328,
            z: 1290,
            image: "santa-claus-icon.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Christmas Village",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                        {
            x: 350,
            z: -4410,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Woodland Mansion",
            textColor: "black", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
                                                                {
            x: 3580,
            z: -780,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.2,
            text: "Grimmy's Swamp",
            textColor: "purple", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        // do not delete the following two closing brackets
    ]
}
