/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "DonJuanDoja",
    "image": "MrNetherite.jpg",
    "x": 3221.75146484375,
    "z": -296.17034912109375
  }
]
